version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: openproject
      POSTGRES_USER: openproject
      POSTGRES_DB: openproject
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

  openproject:
    image: openproject/community:13
    depends_on:
      - db
      - redis
    ports:
      - "8080:80"
    environment:
      OPENPROJECT_HOST__NAME: "75ffdeef397f.ngrok-free.app"
      OPENPROJECT_HTTPS: "true"
      OPENPROJECT_SECRET_KEY_BASE: "secret"
      DATABASE_URL: "postgres://openproject:openproject@db/openproject"
      REDIS_URL: "redis://redis:6379"
    volumes:
      - opdata:/var/openproject/assets

volumes:
  pgdata:
  opdata:
